site_name: "Tese - Anomaly Detection Architecture"
site_description: "Open documentation for our anomaly-detection system: architecture, flows, scoring, and API specs."
site_url: "https://tese-io.github.io/anomaly-detection/"
theme:
  name: "material"
  features:
    - navigation.tabs
    - navigation.sections
    - navigation.expand
    - navigation.top
    - search.highlight
    - search.share
  palette:
    - scheme: default
      primary: blue
      accent: blue
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - scheme: slate
      primary: blue
      accent: blue
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
repo_url: "https://github.com/tese-io/anomaly-detection"
nav:
  - Home: index.md
  - Architecture: architecture.md
  - Technology Stack: technology-stack.md
  - Flows:
      - "Text Q&A Flow": flows/text-qa.md
      - "Document Analysis Flow": flows/document-analysis.md
  - "Scoring & Output": scoring.md
  - Implementation: implementation.md
  - Cost Analysis: cost-analysis.md
  - Sample Usage: sample.md
  - Roadmap: roadmap.md
